[project]
name = "openbb-demo"
version = "0.1.0"
description = "For Demo of OpenBB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "openbb>=4.1.3",
    "pandas>=2.3.1",
    "pyqt5>=5.15.11"
]
